### ISSUE TITLE
Zwanenburg info doesn't work

### ISSUE THREAD

**Issue by iamkarlson** [heyajohnny/afvalinfo#129]
If I put Zwanenburg as a city - integration stopped working. Fixed changing a name to a different Meerlanden provider.

**Comment by heyajohnny** [comment]
Zwanenburg belongs to gemeente 'Haarlemmermeer', so no need to add city 'zwanenburg'. Just use 'haarlemmermeer'.

**Comment by iamkarlson** [comment]
That's true and this is the way how did I fix. The problem is that in the configuration parameter is "city" and not gemeente.

**Comment by heyajohnny** [comment]
The parameter used to be 'city' but I changed it to 'location' some time ago. It was too much of a hassle to keep track of all the cities. I did kept the 'city' parameter valid, so that old configurations still work, but it's just a naming thing. Of course it's nice that you fixed it this way but I'm not going to add all the cities again, I'm sorry...
