### ISSUE TITLE
Haaksbergen

### ISSUE THREAD

**Issue by mmcw** [heyajohnny/afvalinfo#133]
How to get the zip code 7482 GN - 39 working?
It's a zip code in Haaksbergen but whatever I do I do not get any result (other then no values).

Michel

**Comment by heyajohnny** [comment]
It's not working for your address, because it's also not working on the official source: [Twente Milieu](https://www.twentemilieu.nl/enschede/afval/afvalkalender)
I can't help you any further if the source of the data is not working. I advise you to contact 'Twente Milieu' with the issue that your address isn't working.

**Comment by heyajohnny** [comment]
I'm closing this issue, since I can't fix it. The solution to fix this, lies in the hands of Twente Milieu
