### ISSUE TITLE
List not correct

### ISSUE THREAD

**Issue by ErikSiemens** [heyajohnny/afvalinfo#153]
Hello,

In the list Berkelland is noticed as supported, but when I give in my postalcode (in Berkelland) on the web-site, I says "Uw adres is niet bekend bij ons. Neem contact op met uw gemeente"

**Comment by heyajohnny** [comment]
There is support for Berkelland. I have 2 examples for locations in Berkelland:
https://afvalkalender.gemeenteberkelland.nl/adres/7156JS:3
https://afvalkalender.gemeenteberkelland.nl/adres/7271ES:3

Maybe your waste collector is from a neighbor 'gemeente'. It happens if you live near the border of multiple gemeentes.
You can try your address with afvalkalender sites of one of the following neighbor gemeentes:
![image](https://user-images.githubusercontent.com/20553716/102606683-63461780-4127-11eb-91fd-c237dd262cb4.png)

If this doesn't work, please contact the gemeente Berkelland
![image](https://user-images.githubusercontent.com/20553716/102606929-ca63cc00-4127-11eb-9cfe-5a520e369458.png)

**Comment by ErikSiemens** [comment]
7261 xx is not accepted.
Mayby sort it by Borculo, Neede, Eibergen and Ruurlo as saparated towns in stead of Berkelland ?

**Comment by ErikSiemens** [comment]
I treid  mijnafvalwijzer and afvalstoffendienstkalender as mentioned in the readme, and that did not work

**Comment by heyajohnny** [comment]
`7261 xx is not accepted.`
https://afvalkalender.gemeenteberkelland.nl/adres/7261AA:1
https://trashapi.azurewebsites.net/trash?Location=berkelland&ZipCode=7261AA&HouseNumber=1

**Comment by heyajohnny** [comment]
I really don't know what to do with this. You just give half information that stuff doesn't work... And I gave you a solution and working addresses. I'm closing this issue for now...
