### ISSUE TITLE
Cleanprofs sensor unavailable

### ISSUE THREAD

**Issue by mo-harry** [heyajohnny/afvalinfo#406]
I meant: **sensor unknown** 
All the other sensors show a date, except for **Cleanprofs GFT**.  I checked my address on the website https://4fv4l.nl/ and it shows for **GFT/PBD/Papier**. Should Cleanprofs show as well? It's because i searched for Cleanprofs integration for HA, that I found this repository. 

7551AZ
"##" 
hengelo

**Edit/update 2023-12-12 11:40***
It looks like Cleanprofs is having maintenance on their schedule (probably preparing for 2024). Even on their own website it's not possible to get a date from "Reinigingsschema".

**Comment by heyajohnny** [comment]
@mo-harry please let me know if/when it works again

**Comment by heyajohnny** [comment]
Looks like it's still working on my test address, but only for 2023. 2024 data isn't available yet.

**Comment by Rocker20** [comment]
The sensor for GFT has no data here either, but indeed not on the Cleanprofs website either. Since they cleaned that container here last week, I assume that they will not come again this year for this container, and when the data for next year is available the sensor will work again since the RST container is displayed.

**Comment by heyajohnny** [comment]
I'm closing this issue. The data collection works fine, but there are no dates for 2024 yet

**Comment by mo-harry** [comment]
I can confirm that it's working. Got a date today. Great integration 👌
