### ISSUE TITLE
Paper and PMD changed for PreZero

### ISSUE THREAD

**Issue by biocoder-frodo** [heyajohnny/afvalinfo#426]
Since I am a user of https://github.com/xirixiz/homeassistant-afvalwijzer, I noticed i stopped getting updates for the waste collection dates for PMD and paper. I filed a PR [there](https://github.com/xirixiz/homeassistant-afvalwijzer/pull/272) to fix the issue for me.

**Comment by heyajohnny** [comment]
I really don't know what the problem is... 
As far as I can see, everything works just fine:
https://[trashapi.azurewebsites.net/trash?Location=arnhem&ZipCode=6821JD&HouseNumber=1&ShowWholeYear=true](https://trashapi.azurewebsites.net/trash?Location=arnhem&ZipCode=6821JD&HouseNumber=1&ShowWholeYear=true)

https://inzamelwijzer.prezero.nl/eerstvolgende-en-locaties
6821JD 1
