### ISSUE TITLE
Midden-Drenthe en/of Wijster

### ISSUE THREAD

**Issue by MisterMeJ** [heyajohnny/afvalinfo#90]
Can you please support the gemeente Midden-Drenthe and especially the place called Wijster?

Thanks in advance!

**Comment by zoeperman** [comment]
for the site:
https://www.middendrenthe.nl/website/!suite86.scherm0325?mVrg=12635&mAlle=J
9418TE
2

**Comment by heyajohnny** [comment]
I've just added Midden-Drenthe. Please let me know if all works as expected.

**Comment by MisterMeJ** [comment]
Thanks, it's working ;)

Only the 'papier' isn't working, because it's planned from the local school.
Possibility to add, that the paper is collected every 2nd Saturday of the month?

**Comment by heyajohnny** [comment]
> Only the 'papier' isn't working, because it's planned from the local school.
Possibility to add, that the paper is collected every 2nd Saturday of the month?

I'm sorry, but I can't do that. I need to stick to the facts.

Maybe this integration could help you out for the papier collection?
https://github.com/bruxy70/Garbage-Collection/blob/development/README.md

I'm closing this issue, since the original question/answer is solved.

Enjoy and good luck ;)
